RUN_MODE: debug  
db:
  type: ""
  user: ""
  password: ""
  host: "127.0.0.1"
  database: "FreshmanGuidanceProject"
server:
  HTTP_PORT : 8000
  READ_TIMEOUT: 60
  WRITE_TIMEOUT: 60
app:
    PAGE_SIZE: 10