basePath: /api/v1
definitions:
  apis.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  models.Person:
    properties:
      id:
        description: 列名为 `id`
        type: integer
      num_of_know:
        description: 列名为 `num_of_know"`
        type: integer
      num_of_spot:
        description: 列名为 `num_of_spot`
        type: integer
      password:
        description: 列名为 `password`
        type: string
      student_id:
        description: 列名为 `student_id`
        type: string
    type: object
host: "8080"
info:
  contact:
    email: 20364719155@qq.com
    name: gongna
    url: http://www.swagger.io/support
  description: 新生引导项目API
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: 新生引导项目
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: 输入学号和密码登录
      parameters:
      - description: 登录的用户信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
        "400":
          description: '{"Code":"10002", "Message":"Error occurred while binding the
            request body to the struct. "}'
          schema:
            $ref: '#/definitions/apis.Response'
        "500":
          description: '{"Code":"20002", "Message":"Database error:The student ID
            you entered is incorrect, please try again"}'
          schema:
            $ref: '#/definitions/apis.Response'
      summary: Login 用户登录接口
  /auth/spot/:id:
    put:
      consumes:
      - application/json
      description: 在URL中输入地标ID,Body里输入学号就可以实现更新用户个人的探索记录，不论是否探索过该地标都会得到地标的信息，实现了重复探索。
      parameters:
      - description: 只输入学号
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
        "400":
          description: '{"Code":"10002", "Message":"Error occurred while binding the
            request body to the struct. "}'
          schema:
            $ref: '#/definitions/apis.Response'
        "500":
          description: '{"Code":"20002", "Message":"Database error:The student ID
            you entered is incorrect, please try again ."}'
          schema:
            $ref: '#/definitions/apis.Response'
      summary: UpdateSpotAndKnowNum 操作用户移动更新用户探索数据接口
swagger: "2.0"
